name: as_boilerplate_flutter
description: App Shack's template app for Flutter projects
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/analytics_repository
  - packages/api_exceptions
  - packages/app_api
  - packages/app_client
  - packages/app_client_platform_configuration
  - packages/app_l10n
  - packages/app_logging
  - packages/app_ui
  - packages/authentication_api
  - packages/authentication_repository
  - packages/error_tracking
  - packages/external_link_repository
  - packages/user_repository

dependencies:
  analytics_repository:
    path: packages/analytics_repository
  app_api:
    path: packages/app_api
  app_client:
    path: packages/app_client
  app_client_platform_configuration:
    path: packages/app_client_platform_configuration
  app_l10n:
    path: packages/app_l10n
  app_logging: 
    path: packages/app_logging
  app_ui:
    path: packages/app_ui
  authentication_api:
    path: packages/authentication_api
  authentication_repository:
    path: packages/authentication_repository
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.5
  error_tracking:
    path: packages/error_tracking
  external_link_repository:
    path: packages/external_link_repository
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  hydrated_bloc: ^10.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  nested: ^1.0.0
  path_provider: ^2.1.4
  provider: ^6.1.5
  stream_transform: ^2.1.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  melos: ^6.1.0
  mockingjay: ^1.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

# FlutterGen configuration. See readme for more information.
flutter_gen:
  assets:
    enabled: true
  output: lib/generated/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

