name: authentication_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  app_api:
    path: ../app_api
  app_client:
    path: ../app_client
  firebase_auth: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
