name: authentication_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  authentication_api:
    path: ../authentication_api
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
