// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgpXsuar-Vwj0DBecIGxHGJ_J6e3uEae4',
    appId: '1:757683866052:web:356ea684df2a618317fc91',
    messagingSenderId: '757683866052',
    projectId: 'boilerplate-76495',
    authDomain: 'boilerplate-76495.firebaseapp.com',
    storageBucket: 'boilerplate-76495.firebasestorage.app',
    measurementId: 'G-Y77HDT8WJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC40rOJW0IcCW1tWUV9ojTLUu5BXgpJiIE',
    appId: '1:757683866052:android:8e9004455d207d5917fc91',
    messagingSenderId: '757683866052',
    projectId: 'boilerplate-76495',
    storageBucket: 'boilerplate-76495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU3hW3JrwGg6bNVhwB3M49dQTGo5XmcJ4',
    appId: '1:757683866052:ios:a08c4b2b218fb9a017fc91',
    messagingSenderId: '757683866052',
    projectId: 'boilerplate-76495',
    storageBucket: 'boilerplate-76495.firebasestorage.app',
    iosBundleId: 'se.appshack.asboilerplateflutter',
  );
}
