name: app_client
description: A generic Dart client for REST APIs that handles cookie
  authentication. Adds Sentry integration and debug logging of requests out of
  the box.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  api_exceptions:
    path: ../api_exceptions
  app_api:
    path: ../app_api
  cookie_jar: ^4.0.8
  dio: ^5.8.0+1
  dio_cookie_manager: ^3.1.1
  meta: ^1.12.0
  mutex: ^3.1.0
  pretty_dio_logger: ^1.3.1
  sentry_dio: ^8.14.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^7.0.0
