name: app_api
version: 0.0.1
description: App API
homepage: homepage

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.9.5
